name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Runs when you push a tag like v1.0.0

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi  # <-- Create this in repo Settings > Environments

    permissions:
      contents: read
      id-token: write  # Needed for trusted publishing with PyPI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
